# Use the official Node.js image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g ts-node typescript

# Copy the rest of the application source code
COPY . .

# Expose the port the app runs on
# EXPOSE 5000

ENV NODE_ENV=production

# Define the command to start the Node.js server
CMD ["ts-node", "./scripts/runConsumer.ts"]

